apiVersion: v1
name: codedx-tool-orchestration
version: 0.1.0
kubeVersion: ">=1.8.0"
appVersion: "1.0.0"
description: A Helm chart for Code Dx Tool Orchestration
icon: https://codedx.com/wp-content/uploads/2017/03/CodeDx-logo.png
home: https://github.com/codedx/codedx-kubernetes
keywords:
- codedx
- tool
- orchestration
sources:
maintainers:
- name: tylercamp
  email: support@codedx.com
- name: ssalas
  email: support@codedx.com
