apiVersion: v2
name: codedx
version: 0.8.0
appVersion: "4.4.3"
description: A Helm chart for Code Dx
icon: https://codedx.com/wp-content/uploads/2017/03/CodeDx-logo.png
home: https://github.com/codedx/codedx-kubernetes
keywords:
- codedx
- security
- sast
- scan
- analysis
sources:
- https://hub.docker.com/r/codedx/codedx-tomcat
- https://hub.docker.com/_/tomcat/
- https://hub.docker.com/r/bitnami/mariadb
dependencies:
- name: mariadb
  version: 5.5.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
maintainers:
- name: tylercamp
  email: support@codedx.com
- name: ssalas
  email: support@codedx.com
