apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-tiller
rules:
- apiGroups:
  - ""
  - rbac.authorization.k8s.io
  - policy
  - extensions
  - networking
  - apps
  - networking.k8s.io
  - apiextensions.k8s.io
  - apiregistration.k8s.io
  - admissionregistration.k8s.io
  - storage.k8s.io
  - argoproj.io
  resources: ['*']
  verbs: ['*']

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-tiller
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-tiller
subjects:
  - kind: ServiceAccount
    name: helm-tiller
    namespace: kube-system