{{- if .Values.rbac.codedx.podSecurityPolicy.create -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "codedx.rbac.psp.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes: ["persistentVolumeClaim", "configMap", "secret"]
  hostNetwork: false
  hostIPC: false
  hostPID: false
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  runAsUser:
    # TODO - Disable running as root user; enabled for now since I can't find an existing, simple, minimal non-root image
    #        When disabled, update the codedx-tomcat-deployment container templates to have "securityContext: { runAsUser: <uid> }"
    #        to force the container to run as the specified user (if necessary)
    #rule: MustRunAsNonRoot
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
{{- end -}}