apiVersion: v1
kind: Service
metadata:
  name: {{ include "codedx.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "codedx.name" . }}
    helm.sh/chart: {{ include "codedx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "frontend"
spec:
  type: LoadBalancer
  ports:
  - name: {{ .Values.codedxTomcatPort | quote }}
    port: {{ .Values.codedxTomcatPort }}
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "codedx.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "frontend"
status:
  loadBalancer: {}
