{{- if .Values.podSecurityPolicy.enabled -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "codedx.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "codedx.name" . }}
    helm.sh/chart: {{ include "codedx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "frontend"
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes: ["persistentVolumeClaim", "configMap", "secret"]
  hostNetwork: false
  hostIPC: false
  hostPID: false
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  runAsUser:
    # TODO - Disable running as root user; enabled for now since I can't find an existing, simple, minimal non-root image
    #        When disabled, update the codedx-tomcat-deployment container templates to have "securityContext: { runAsUser: <uid> }"
    #        to force the container to run as the specified user (if necessary)
    #rule: MustRunAsNonRoot
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
{{- end -}}