{{- if .Values.podSecurityPolicy.enabled -}}
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "codedx.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "codedx.name" . }}
    helm.sh/chart: {{ include "codedx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "frontend"
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes: []
  hostNetwork: false
  hostIPC: false
  hostPID: false
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
{{- end -}}