apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "codedx.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "codedx.name" . }}
    helm.sh/chart: {{ include "codedx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "codedx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "frontend"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "codedx.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "frontend"
    spec:
      containers:
      - env:
        - name: SUPERUSER_NAME
          value: "admin"
        - name: SUPERUSER_PASSWORD
          value: {{ .Values.codedxAdminPassword | quote }}
        image: {{ .Values.codedxTomcatImage | quote }}
        name: "{{ include "codedx.name" . }}"
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /opt/codedx
          name: {{ include "volume.fullname" . | quote }}
        {{ if .Values.codedx.propsFile -}}
        - mountPath: /opt/codedx/codedx.props
          name: codedx-props-configmap-volume
          subPath: codedx.props
        {{- end }}
        {{ if .Values.codedx.licenseFile -}}
        - mountPath: /opt/codedx/license.lic
          name: codedx-license-secret-volume
          subPath: license.lic
        {{- end }}
      initContainers:
        - name: {{ include "dbinit.fullname" . }}
          image: "ubuntu:18.04"
          command: ["bash", "-c", "for i in {1..60}; do if (cat < /dev/tcp/{{ .Release.Name }}-mariadb/3306); then echo 'Successfully connected to MariaDB port'; exit 0; else echo 'Retrying database connection...'; sleep 2; fi; done; echo 'MariaDB is unavailable'; exit 1"]
      restartPolicy: Always
      volumes:
      - name: {{ include "volume.fullname" . | quote }}
        persistentVolumeClaim:
          claimName: {{ include "volume.fullname" . | quote }}
      {{ if .Values.codedx.propsFile -}}
      - name: codedx-props-configmap-volume
        configMap:
          name: {{ include "codedx.name" . }}-configmap
          items:
          - key: codedx.props
            path: codedx.props
      {{- end }}
      {{ if .Values.codedx.licenseFile -}}
      - name: codedx-license-secret-volume
        secret:
          secretName: {{ include "codedx.fullname" . }}-license-secret
          items:
          - key: license.lic
            path: license.lic
      {{- end }}

status: {}
