{{- if .Values.ingress.enabled -}}
{{- range .Values.ingress.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "codedx.commonLabels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.key: {{ .key | trim }}
  tls.crt: {{ .certificate | trim }}
---
{{- end -}}
{{- end -}}