{{- if .Values.networkPolicy.codedx.create -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ include "codedx.fullname" . }}-codedx-netpolicy"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      codedx.com-instance: {{ .Release.Name | quote }}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: mariadb
          release: {{ .Release.Name | quote }}
    ports:
    - port: 3306
  - ports:
    {{- include "netpolicy.dns.ports" . | nindent 4 -}}
{{- if .Values.networkPolicy.codedx.ingressSelectors }}
  ingress:
  - from:
{{ toYaml .Values.networkPolicy.codedx.ingressSelectors | indent 4 -}}
    ports:
    - port: 9090
{{- else }}
  ingress: []
{{- end -}}
{{- end -}}