{{- if .Values.ingress.enabled -}}
{{- range .Values.ingress.hosts -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" (include "codedx.name" $) .name | trunc 63 | trimSuffix "-" | quote }}
  labels:
    {{- include "codedx.commonLabels" $ | nindent 4 }}
  annotations:
{{ toYaml $.Values.ingress.annotations | trim | indent 4 }}
spec:
  {{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ .tlsSecret }}
  {{- end }}
  rules:
  - host: {{ .name }}
    http:
      paths:
      - path: /codedx
        backend:
          serviceName: {{ include "codedx.fullname" $ }}
          servicePort: {{ $.Values.codedxTomcatPort }}
---
{{- end -}}
{{- end -}}