{{- if .Values.ingress.enabled -}}
{{- range .Values.ingress.hosts -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" (include "codedx.name" $) .name | trunc 63 | trimSuffix "-" | quote }}
  labels:
    {{- include "codedx.commonLabels" $ | nindent 4 }}
  annotations:
    {{ if $.Values.ingress.autoRedirect -}}
    nginx.ingress.kubernetes.io/app-root: /codedx
    {{- end }}
    {{ if not .tls -}}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    # Increase timeout duration for Code Dx live updates
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    # Remove file size limit, Code Dx enforces this internally
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  {{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    secretName: {{ .tlsSecret }}
  {{- end }}
  rules:
  - host: {{ .name }}
    http:
      paths:
      - path: /codedx
        backend:
          serviceName: {{ include "codedx.fullname" $ }}
          servicePort: {{ $.Values.codedxTomcatPort }}
---
{{- end -}}
{{- end -}}