apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "volume.fullname" . }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
