{{- define "codedx.mariadb.propsTemplate" -}}
# MariaDB creds stored in a secret
swa.db.user = root
swa.db.password = TPL_K8S_DB_PASSWORD
{{- end -}}
{{- $propsTemplate := (include "codedx.mariadb.propsTemplate" .) -}}
{{- $props := ($propsTemplate | replace "TPL_K8S_DB_PASSWORD" .Values.rootUserDatabasePassword) -}}

{{- if .Values.codedx.props.mariadb.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codedx.mariadb.secretName" . }}
  labels:
    helm.sh/chart: {{ include "codedx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: codedx
  annotations:
{{ toYaml .Values.codedx.props.mariadb.annotations | indent 4 }}
type: Opaque
data:
  codedx.mariadb.props: {{ $props | b64enc }}
{{- end -}}