{{- if and .Values.codedx.licenseFile (not .Values.codedx.licenseSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codedx.license.secretName" . }}
  labels:
    helm.sh/chart: {{ include "codedx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "license-secret"
type: Opaque
data:
  license.lic: {{ .Files.Get .Values.codedx.licenseFile | b64enc | quote }}
{{- end -}}