{{- $saName := (include "codedx-tool-orchestration.serviceAccountName" .) | quote -}}
{{- $hookRoleName := (printf "%s-%s" (include "codedx-tool-orchestration.fullname" .) "-hook-role") | quote -}}
{{- $hookRoleBindingName := (printf "%s-%s" (include "codedx-tool-orchestration.fullname" .) "-hook-binding") | quote -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $hookRoleName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx-tool-orchestration.commonLabels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "delete"]
{{- if .Values.podSecurityPolicy.tws.bind }}
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ include "codedx-tool-orchestration.rbac.psp.tws.name" . | quote }}
{{- end }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $hookRoleBindingName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx-tool-orchestration.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $hookRoleName }}
subjects:
- name: {{ $saName }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
