{{- if .Values.openshift.createSCC -}}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "codedx.scc" . }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
groups: []
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1000
  uidRangeMax: 1001
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "codedx.serviceAccountName" . }}
{{ if .Values.mariadb.enabled -}}
- system:serviceaccount:{{ .Release.Namespace }}:{{ include "mariadb.ref.serviceAccountName" . }}
{{- end }}
volumes:
- configMap
- emptyDir
- persistentVolumeClaim
- secret
{{- end -}}