{{- if and .Values.codedxProps.file (not .Values.codedxProps.configMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codedx.props.configMapName" . | quote }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.codedxProps.annotations | trim | indent 4 }}
data:
  {{- /* We use `replace` here instead of usual file templating. A `codedx.props` file can contain documenting */ -}}
  {{- /* comments with sample parameters named ie "{{project.name}}". Rather than try to trim comments from the output */ -}}
  {{- /* or change the `codedx.props` sample file, we use a simple text-replace for flexibility. */ -}}
  {{- $dbUrl := (printf "jdbc:mysql://%s-mariadb/codedx" .Release.Name) -}}
  {{- if not .Values.mariadb.enabled -}}
  {{-   $dbUrl = (required ".Values.codedxProps.dbconnection.externalDbUrl must be specified when using an external MariaDB instance" .Values.codedxProps.dbconnection.externalDbUrl) -}}
  {{- end -}}

  {{- if contains "?" $dbUrl -}}
  {{-   $dbUrl = (printf "%s&" $dbUrl) -}}
  {{- else -}}
  {{-   $dbUrl = (printf "%s?" $dbUrl) -}}
  {{- end -}}  

  {{- $sessionVariables := "sessionVariables=sql_mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'" -}}
  {{- $dbUrl = (printf "%s%s" $dbUrl $sessionVariables) -}}

  {{- $propsContents := (required "codedx.props cannot be an empty file!" (.Files.Get .Values.codedxProps.file)) -}}

  {{- $propsContents := ($propsContents | replace "TPL_K8S_DB_URL" $dbUrl) }}
  codedx.props: |-
    {{- $propsContents | nindent 4 }}

  tomcat.env: |-
    CATALINA_OPTS='{{ include "codedx.props.params.combined" . }}'
    CATALINA_OPTS="$CATALINA_OPTS {{ default "" .Values.codedxJavaOpts }}"
    CATALINA_OPTS="$CATALINA_OPTS -Djavax.net.ssl.keystorepassword=$KEYSTORE_KEY"

  codedx-ml.props: |-
    codedx.external-url = {{ include "codedx.serviceurl" . | quote }}

  {{ if .Values.loggingConfigFile -}}
  logback.xml: |-
    {{- .Files.Get .Values.loggingConfigFile | nindent 4 -}}
  {{- end -}}

  {{ range .Values.codedxProps.extra }}
  {{ if eq (required "codedxProps.extra entries must have a 'type' defined!" .type) "values" -}}
  {{ .key }}: |-
    {{- range .values -}}
    {{- . | nindent 4 }}
    {{- end -}}
  {{- end }}
  {{- end }}

  {{ range .Values.codedxProps.internalExtra }}
  {{ if eq (required "codedxProps.internalExtra entries must have a 'type' defined!" .type) "values" -}}
  {{ .key }}: |-
    {{- range .values -}}
    {{- . | nindent 4 }}
    {{- end -}}
  {{- end }}
  {{- end }}

  {{ if .Values.authentication.saml.enabled -}}
  saml-idp.xml: |-
    {{- (required "authentication.saml.samlIdpXmlFile cannot be an empty file!" (.Files.Get .Values.authentication.saml.samlIdpXmlFile)) | nindent 4 }}

  codedx-saml.props: |-
    auth.saml2.identityProviderMetadataPath = /opt/codedx/saml-idp.xml
    auth.hostBasePath = {{ .Values.authentication.hostBasePath | quote }}
    auth.saml2.entityId = {{ .Values.authentication.saml.appName | quote }}
  {{- end -}}
{{- end -}}