apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "codedx-tool-orchestration.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx-tool-orchestration.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "codedx-tool-orchestration.name" . | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "codedx-tool-orchestration.commonLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        codedx.com-instance: {{ .Release.Name | quote }}
    spec:
      {{ if .Values.toolServiceImagePullSecrets -}}
      imagePullSecrets: {{ toYaml .Values.toolServiceImagePullSecrets | nindent 6 -}}
      {{ end -}}
      serviceAccountName: {{ include "codedx-tool-orchestration.serviceAccountName" . | quote }}
      serviceAccount: {{ include "codedx-tool-orchestration.serviceAccountName" . | quote }}
      containers:
      - name: tool-service
        image: {{ .Values.toolServiceImageName }}
        command: ["/opt/codedx/service/bin/service"]
        args: ["-adminApiKeyPath", "/opt/codedx/service/secrets/adminApiKey",
          "-codeDxBaseUrl", "{{ .Values.codeDxBaseUrl }}",
          "-imageNameCodeDxTools", "{{ .Values.imageNameCodeDxTools }}",
          "-imageNameCodeDxToolsMono", "{{ .Values.imageNameCodeDxToolsMono }}",
          "-imageNameNewAnalysis", "{{ .Values.imageNameNewAnalysis }}",
          "-imageNameSendResults", "{{ .Values.imageNameSendResults }}",
          "-imageNameZap", "{{ .Values.imageNameZap }}",
          "-imagePullSecretKey", "{{ .Values.imagePullSecretKey }}",
          "-kubeconfigPath", "",
          "-kubernetesNamespace", "{{ .Release.Namespace }}",
          "-logFile", "/opt/codedx/service/logs/service.log",
          "-minioAdminPasswordPath", "/opt/codedx/service/secrets/minioAdminPassword",
          "-minioAdminUsernamePath", "/opt/codedx/service/secrets/minioAdminUsername",
          "-minioClientPath", "/opt/codedx/service/tools/mc",
          "-minioClusterEndpoint", "{{ template "minio.ref.fullname" . }}:{{.Values.minio.service.port}}",
          "-minioEndpoint", "{{ template "minio.ref.fullname" . }}:{{.Values.minio.service.port}}",
          "-port", "{{ .Values.toolServicePort }}",
          "-workDir", "/opt/codedx/service/work"]
        securityContext:
          # ID of "service" account in tool orchestration image
          runAsUser: 1000
        volumeMounts:
        - name: tool-service-secret-volume
          mountPath: "/opt/codedx/service/secrets"
          readOnly: true
        - name: logs
          mountPath: "/opt/codedx/service/logs"
          readOnly: false
        ports:
        - containerPort: 3333
          name: http
      - name: tool-service-log
        image: {{ .Values.logImageName }}
        args: [/bin/sh, -c, 'tail -n+1 -f /var/log/service/service.log']
        securityContext:
          # match ID of service account so we can read logs
          runAsUser: 1000
        volumeMounts:
        - name: logs
          mountPath: /var/log/service
          readOnly: true
      volumes:
      - name: tool-service-secret-volume
        secret:
          secretName: tool-service-secret
      - name: logs
        emptyDir: {}
