apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "codedx-tool-orchestration.workflow.priorityClassName" . | quote }}
value: {{ .Values.priorityClass.workflowValue }}
globalDefault: false
description: "The priority class for Code Dx Tool Orchestration workflows."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "codedx-tool-orchestration.service.priorityClassName" . | quote }}
value: {{ .Values.priorityClass.serviceValue }}
globalDefault: false
description: "The priority class for the Code Dx Tool Orchestration service."
