apiVersion: v1
kind: Service
metadata:
  name: {{ include "codedx-tool-orchestration.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx-tool-orchestration.commonLabels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: {{ required "toolServicePort is required" .Values.toolServicePort }}
    protocol: TCP
    targetPort: 3333
  selector:
    app.kubernetes.io/name: {{ include "codedx-tool-orchestration.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
