apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "codedx.priorityClassName" . | quote }}
value: {{ .Values.priorityClassValue }}
globalDefault: false
description: "The priority class for the Code Dx web application."
