apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codedx.mariadb.secretName" . | quote }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
type: Opaque
data:
  codedx.mariadb.props: {{ (include "codedx.mariadb.propsTemplate" .) | b64enc }}
