{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codedx.adminSecretName" . | quote }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ required "existing secret not found, so expected to find value for codedxAdminPassword" .Values.codedxAdminPassword | b64enc | quote }}
{{- end }}