# Default values for codedx.

codedxTomcatImage: codedx/codedx-tomcat:v3.5.3

codedxTomcatPort: 9090

rootUserDatabasePassword: 5jqJL2b8hqn3
codedxAdminPassword: wtKzR4F8o64A

ingress:
  enabled: false
  hosts:
  # - name: codedx.local
  #   tls: true
  #   # TODO?
  #   #certManager: true
  #   tlsSecret: tls-secret
  
  # Use to auto-create secrets with the given properties if they don't yet exist
  # secrets:
  # - name:
  #   key:
  #   certificate: 

service: {}
  # Specify the type of service that will be exposing Code Dx. Acceptable values are:
  # ClusterIP, NodePort, LoadBalancer
  #
  # If left unassigned, this will have one of the following defaults:
  #   "ClusterIP"    - If "ingress.enabled" = true
  #   "LoadBalancer" - If "ingress.enabled" = false
  #
  #type: LoadBalancer

mariadb:
  db:
    name: codedx
  rootUser:
    password: 5jqJL2b8hqn3
  replication:
    password: 11uAQKLgv4JM
  master:
    config: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      optimizer_search_depth=0
      innodb_flush_log_at_trx_commit=0

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
  slave:
    config: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      optimizer_search_depth=0
      innodb_flush_log_at_trx_commit=0

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
