# Default values for codedx.

codedxTomcatImage: codedx/codedx-tomcat:v3.5.3

codedxTomcatPort: 9090

rootUserDatabasePassword: 5jqJL2b8hqn3
codedxAdminPassword: wtKzR4F8o64A

codedx:
  # Specify 'propsFile' to create a config-map for Code Dx based on the given 'codedx.props' file
  propsFile: codedx.props

  # Specify 'propsConfigMap' to use an existing config-map for Code Dx. This config-map MUST contain
  # a key named 'codedx.props' with the contents of the properties to use. Check the provided
  # 'codedx.props' file included with this chart and use the same 'swa.db.*' values to ensure that
  # Code Dx properly connects to the generated MariaDB instances.
  # 
  # (If both propsFile and propsConfigMap are specified, the existing 'propsConfigMap' will be used
  #  and no new config-map will be created.)
  #propsConfigMap: my-codedx-config-map

  # Specify 'licenseSecret' to use an existing secret for the Code Dx license. This secret MUST
  # contain a key named 'license.lic' with the contents of the license to use.
  licenseSecret: my-codedx-license-secret

  # Specify 'licenseFile' to automatically create a secret based on the given license
  # (If both are specified, the existing 'licenseSecret' will be used and no new secret
  #  will be created.)
  #licenseFile: my-license-file

mariadb:
  db:
    name: codedx
  rootUser:
    password: 5jqJL2b8hqn3
  replication:
    password: 11uAQKLgv4JM
  master:
    config: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      optimizer_search_depth=0
      innodb_flush_log_at_trx_commit=0

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
  slave:
    config: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      optimizer_search_depth=0
      innodb_flush_log_at_trx_commit=0

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
